### ISSUE TITLE
Battery not loading RROS Rolex 7.0.2

### ISSUE THREAD

**Issue by trettach** [ResurrectionRemix-Devices/device_xiaomi_rolex#1]
Since Resurrection Remix Pie Ver 7.0.2, my Redmi 4A did not charge battery sufficiently. For example stayed all night at 25 % battery power, while connected to loading cable.

I did dirty install first, but after clean install (wiped dalvik, cache, /data/data), the problem persisted.

Downgrade to RR-P-v7.0.1-20190411-rolex-Official solved my problem finally!

**Comment by najahiiii** [comment]
will be fixed on next update.
