### ISSUE TITLE
Wlan Config gets garbled in current release

### ISSUE THREAD

**Issue by trettach** [ResurrectionRemix-Devices/device_xiaomi_rolex#2]
In clean install of RR-P-v7.0.2-20190513-rolex-Official wlan configuration file

- /data/misc/wifi/WifiConfigStore.xml

gets overwritten with apparently random reference to /data/app folder. Example:
/data/app/jackpal.androidterm-o8p0l7VpQa3nyK2YIN8QeQ==/li
b/arm^@^@^@^@^@^@^@^@...

I had this several times with three different apps paths.

In the consequence wlan is not possible to configure or connect, until /data/misc/wifi/WifiConfigStore.xml is manualle deleted and rebooted. Then WifiConfigStore.xml recovers to standard contents, and can be written into by wlan settings.

I did chmod 400 WifiConfigStore.xml and as a precaution chattr +i WifiConfigStore.xml
Edit: to no avail. File was overwritten at reboot with:
/data/app/org.thoughtcrimesms-NhfUY1suAD1MJ4IgIYWQ==/lib/arm^@^@^@^@^@^@^@^@^@^@...

**Comment by trettach** [comment]
I wondered, if my file system might be broken. Wiped with "fix file system" and restored backup without img restoring function.

After this, the config file becomes not garbled anymore, but overwritten with a clean empty template after reboot.

Yes, I have mostly no idea of what is going on. If nobody else is reporting this, it is my individual issue.

Now I made wifi config, chattr +i WifiConfigStore.xml. And WLAN works also after reboot.

Interesting to me logcat info now:
[logcat-wifi-config-manager.txt](https://github.com/ResurrectionRemix-Devices/device_xiaomi_rolex/files/3193959/logcat-wifi-config-manager.txt)

Maybe I was also having an issue with AtomicFile functions.

05-18 12:31:18.135  1827  2176 D WifiConfigStore: Reading from stores completed in 17 ms.
05-18 12:31:18.584  1827  2176 D WifiConfigStore: Reading from user store completed in 3 ms.
05-18 12:31:18.588  1827  2176 W AtomicFile: Couldn't rename file /data/misc/wifi/WifiConfigStore.xml to backup file /data/misc/wifi/WifiConfigStore.xml.bak
05-18 12:31:18.590  1827  2176 E WifiConfigManager: Writing to store failed. Saved networks maybe lost!
05-18 12:31:18.590  1827  2176 E WifiConfigManager: java.io.IOException: Couldn't create directory /data/misc/wifi/WifiConfigStore.xml
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.internal.os.AtomicFile.startWrite(AtomicFile.java:75)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigStore$StoreFile.writeBufferedRawData(WifiConfigStore.java:544)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigStore.writeBufferedData(WifiConfigStore.java:331)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigStore.write(WifiConfigStore.java:262)05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigManager.saveToStore(WifiConfigManager.java:2920)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigManager.handleUserUnlockOrSwitch(WifiConfigManager.java:2540)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiConfigManager.handleUserUnlock(WifiConfigManager.java:2607)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.server.wifi.WifiStateMachine$DefaultState.processMessage(WifiStateMachine.java:3529)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:992)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:809)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at android.os.Handler.dispatchMessage(Handler.java:106)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at android.os.Looper.loop(Looper.java:193)
05-18 12:31:18.590  1827  2176 E WifiConfigManager:     at android.os.HandlerThread.run(HandlerThread.java:65)
05-18 12:31:31.572  1827  2176 W AlarmManager: Unrecognized alarm listener com.android.server.wifi.WifiConfigStore$1@f5b0774
05-18 12:31:31.572  1827  2176 W AtomicFile: Couldn't rename file /data/misc/wifi/WifiConfigStore.xml to backup file /data/misc/wifi/WifiConfigStore.xml.bak
05-18 12:31:31.573  1827  2176 E WifiConfigStore: Buffered write failed
05-18 12:31:31.573  1827  2176 E WifiConfigStore: java.io.IOException: Couldn't create directory /data/misc/wifi/WifiConfigStore.xml
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at com.android.internal.os.AtomicFile.startWrite(AtomicFile.java:75)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at com.android.server.wifi.WifiConfigStore$StoreFile.writeBufferedRawData(WifiConfigStore.java:544)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at com.android.server.wifi.WifiConfigStore.writeBufferedData(WifiConfigStore.java:331)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at com.android.server.wifi.WifiConfigStore.access$000(WifiConfigStore.java:56)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at com.android.server.wifi.WifiConfigStore$1.onAlarm(WifiConfigStore.java:125)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at android.app.AlarmManager$ListenerWrapper.run(AlarmManager.java:245)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at android.os.Handler.handleCallback(Handler.java:873)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at android.os.Handler.dispatchMessage(Handler.java:99)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at android.os.Looper.loop(Looper.java:193)
05-18 12:31:31.573  1827  2176 E WifiConfigStore:       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by najahiiii** [comment]
Thank you very much for reporting. I'll fix it right now..
